### PR TITLE
Add normalization

### PR DESCRIPTION
**Pull request by pierroz127**
- Fixes https://github.com/nabla/health/issues/34413

## Summary
- Use all parameters in note generation (locale, style, template)
- Generate normalized data 

Screenshot 2024-04-25 at 12 10 12

### CODE REVIEW

**Comment by gregoirenovel** [comment]
Why not a button "Generate normalized data" like the others?
And to always have "1 button = 1 specific API call"

**Comment by pierroz127** [comment]
> Why not a button "Generate normalized data" like the others? And to always have "1 button = 1 specific API call"

I just mimicked what we had on our app but ok

**Comment by gregoirenovel** [comment]
> I just mimicked what we had on our app but ok

Yes and no, the ICD-10 section at the bottom of the note in our app only shows parts of the normalized data.

**Comment by pierroz127** [comment]
Screenshot 2024-04-25 at 15 51 38

**Review by AchrafAmil — APPROVED** [review]
awesome, thanks a lot! 🚀

**Pull request merged**
